sqlLite 3
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3


# #mysql
# development:
#   adapter: mysql2
#   encoding: utf8
#   database: cnab
#   username: root
#   password: root
#   host: localhost


#mysql
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
